soto-project/soto-core

Sources/AWSSDKSwiftCore/Decoder/DictionaryDecoder.swift

…nse that become singleValue depends on contents

stop throwing DecodingError._typeMismatch to decode property in response that become singleValue depends on contents

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Serializer/XMLNodeSerializer.swift
Sources/AWSSDKSwiftCore/XML/XMLParser.swift

This PR relates https://github.com/noppoMan/aws-sdk-swift/issues/61.
* If the response type has `payloadPath`, the responded body data should be handled as buffer not external representation.
* More robust mapping process between external representation and object. It's necessary for successfully decoding with Swift's Decoder
* Convert the value in XML to JSON native type if the value is meaningful for JSON. (e.g, "null" => null, "3.1" => Double: 3.1)
* Convert the header value to number if it can cast Double. (e.g "1" => Int: 1, "1.1" => Double: 1.1)

Improve external representation and object mapping

---

Package.resolved
Package@swift-4.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/Credential.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift
Tests/AWSSDKSwiftCoreTests/SignersV4Tests.swift
Tests/LinuxMain.swift

point to Prorsum package with fix for get ecs credentials
detect if AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is present
and set static var serviceHost to enum MetaDataServiceHost
determine logic to getCredentials in MetaDataService from
serviceHost
add support for Expiration on Credential
check if Credential is nearExpiration and call getCredential
if within 5 mins or Expiration is past

add support for iam role for tasks

---

Sources/AWSSDKSwiftCore/Serializer/XMLNodeSerializer.swift
Tests/AWSSDKSwiftCoreTests/SerializersTests.swift

My calls to [`DescribeAutoScalingGroups`](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeAutoScalingGroups.html) returned a value of `False`. This caused a crash via `JSONDecoder`, which could not handle the input (and was expecting a lowercased `false`).
This change now defensively handles the case where we receive a capitalized boolean value back from the API.

We should always lowercase true and false when converting JSON

---

Sources/AWSSDKSwiftCore/MetaDataService.swift

This should allow us to properly parse the timestamp in MetadataService when developing locally.
This attempts to close https://github.com/swift-aws/aws-sdk-swift-core/issues/32

Take advantage of ISO8601DateFormatter on macOS 10.12 and greater.

---

Sources/AWSSDKSwiftCore/Serializer/XMLNodeSerializer.swift
Tests/AWSSDKSwiftCoreTests/SerializersTests.swift
Tests/AWSSDKSwiftCoreTests/XMLParserTests.swift

When calling ELB's `describe-load-balancers`, I found we were parsing the XML incorrectly, creating JSON like this:
```
"BackendServerDescriptions":[{"InstancePort":8080,"PolicyNames":{}},{"InstancePort":8443,"PolicyNames":{}}]
```
Converting that into the respective shape didn't work as expected, since we're somehow turning `<PolicyNames><member>TFEnableProxyProtocol</member></PolicyNames>` into `"PolicyNames":{}`. 
This is [specified correctly](https://github.com/aws/aws-sdk-go/blob/master/models/apis/elasticloadbalancing/2012-06-01/api-2.json#L1357) in our JSON definition, so it's definitely how we're converting it.
I've just submitted the below test case in the hopes that someone else knows how to fix this while I sleep on it 🤔

Improve XML list parsing

---

Package.resolved
Package.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/Credential.swift
Tests/AWSSDKSwiftCoreTests/CredentialTests.swift

I've added INIParser as a dependency for reading the config files.
I also removed the SharedCredential.default property since I was unsure what it was intended for. Instead when AWSClient is created, it will attempt to create a SharedCredentials object.

Add shared credentials support

---

Package.resolved
README.md

nio-ssl 1.3.1 introduces a compilation warning, but I think this is ok based on 
https://github.com/apple/swift-nio-ssl/issues/44

update nio and nio-ssl to latest 1.x versions

---

.travis.yml
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

I was trying to [upload a certificate](https://docs.aws.amazon.com/IAM/latest/APIReference/API_UploadServerCertificate.html) which included a `=` and it was failing AWS' parsing.

URLEncode the equals sign _just_ in the value of a query string

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

if the shape has a payload path and it defines a shape, we need to properly serialize that shape.
unfortunately, when the protocol is JSON convincing the compiler that the reflection object is a generic AWSShape that's encodable is not as simple as a switch statement... so we need to serialize the full input to JSON, back to a dictionary, parse the payloadPath out and serialize that... a bit ugly, but effective.
Thank you to @adam-fowler for finding this bug and sharing the solution.

properly serialize the payloadPath object as json / xml

---

Sources/AWSSDKSwiftCore/AWSClient.swift

Reading of credentials is now in the order suggested in Issue #48

Updated credentials reading order

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Decoder/UntypedDictionaryDecoder.swift
Sources/AWSSDKSwiftCore/Encoder/AWSShapeEncoder.swift
Sources/AWSSDKSwiftCore/Serializer/XMLNodeSerializer.swift
Sources/AWSSDKSwiftCore/XML/XMLNode.swift
Sources/AWSSDKSwiftCore/XML/XMLParser.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/SerializersTests.swift
Tests/AWSSDKSwiftCoreTests/XMLParserTests.swift

These changes fix a number of issues relating to serialization of AWSShapes as queries and parsing of response XML.
1. UntypedDictionaryDecoder: Currently when response xml is parsed, it is converted to json, then a dictionary and then into AWSShapes. During the conversion from xml to json the types of values are guessed by their contents. So a number becomes an integer, "true" becomes a boolean etc. This causes an issue when a number is used for a string. Although we want a string we get integer and then we get a typeMismatch error during the decode to AWSShape. I have fixed this by not assuming types during the xml to json conversion (everything is a string). Then I added an UntypedDictionaryDecoder which is an exact replica of the DictionaryDecoder except the unbox functions attempt to …

Fixes various query serialization issues

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

If you have a path that includes a query parameter without an "=" sign the stringToSign that is built during the V4 signature construction is wrong. The code was outputting the query parameter without the "=" sign. AWS expects the "=" to be there. 
It seems that this only affects a number of S3 calls and a couple of calls in Cloudfront. I have checked both of systems and the code fixes the issue. This fixes https://github.com/swift-aws/aws-sdk-swift/issues/117

Incorrect stringToSign created for API calls that include query parameters without assignation

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Sources/AWSSDKSwiftCore/Signers/V4.swift
Tests/AWSSDKSwiftCoreTests/SignersV4Tests.swift

Hi, I'm back.
Today I tried to request dynamodb-local through custom endpoint like...
```
DynamoDB(endpoint: "http://localhost:8000")
```
But current AWSClient seems to lost the function of custom endpoint.
(`MetaDataService.getCredential()` is always called and attempt to connect `169.254.x.x` when the credential is empty.)
So I fixed it to connect the custom endpoint when it's given.

Resurrect custom endpoint request

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTPClient.swift

If there was no connection a noConnection error is thrown and the ClientBootstrap channel is never initialized. This means the response eventloopFuture is never connected up and the code will hang when you wait on it. 
To fix this I have added a thenIfErrorThrowing to catch the error and then set the response to fail inside there. 
Also added code to ensure the client.close() is always run

Fail response future when connection fails

---

Sources/AWSSDKSwiftCore/Signers/V4.swift

It is first encoded in AWSClient.createAWSRequest() when URLComponents.queryItems is set. Then in V4.signedURL() when building the query array for the signature it is percent encoded again. This gives
us %253D instead of %3D. Therefore the signature calculation is incorrect. I fixed this by undoing the encoding before re-encoding with V4.awsUriEncode().
This fixes S3.listObjectV2() when you are supplying a continuation token that contains an '=' sign.

Fix '=' sign being percent encoded twice

---

Sources/AWSSDKSwiftCore/Signers/V4.swift

Avoid warning on Xcode 11. This variable should be immutable.

Avoid warning on Xcode

---

Sources/AWSSDKSwiftCore/AWSClient.swift

The query string returned by AWSClient.urlEncodedQueryParams() did not percent encode enough characters. In particular it didn't encode the + sign. The function used URLComponents() to generate it's query params text. This would percent encode some characters but not all. I couldn't send it already percent encoded text as that percent encode the '%' signs. So instead I wrote a version which didn't use the URLComponents at all.
This fixes https://github.com/swift-aws/aws-sdk-swift/issues/107

Add percent encoded characters for urlEncodedQueryParams

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Message/Body.swift

This fixes a crash most likely related to https://github.com/apple/swift-corelibs-foundation/pull/1887.
We need to ensure we hold a reference to the XMLDocument if we are processing XMLNodes inside it. I've done this by allowing Body to hold an XMLDocument.
The crash was occurring in S3Tests.testListObjects() on aws-sdk-swift. AWSClient.validateBody() would create a XMLDocument and return the rootElement(). Given the bug detailed above this would mean the XMLDocument and its contents were free to be deleted, even though we had a XMLElement referencing it.

Fix crash on Linux 4.2 while handling XML

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTPClient.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift

If port is included in the hostname that is given to the HttpClient then
ensure that is included in the "Host" entry of the headers. 
This fixes https://github.com/swift-aws/aws-sdk-swift-core/issues/94
I have verified this code works with standard AWS requests and also that it works with fakes3 and dynamodb_local.

Deal with hostnames which include port in them

---

Sources/AWSSDKSwiftCore/XML.swift

Not just whitespace. This doesn't seem to break anything but it would be tidier if we didn't parse newlines as content.

Remove whitespacesAndNewlines when parsing XML

---

Sources/AWSSDKSwiftCore/Signers/V4.swift

The "x-amz-security-token" header value was being added after the "Authorization" header value was calculated. This was then giving the error
```
accessDenied(message: Optional("RequestId: 4059FAA108A45F89, 
HeadersNotSigned: x-amz-security-token, 
Message: There were headers present in the request which were not signed, 
HostId: p013uVEP7DHgqGkbCe/zsjuASVE0b9h9a7Gb37OfnuPmFnNeMZ5VnILzvi9orDLzHtfn1yNEzLA="))
```
This pull request moves the adding of the "x-amz-security-token" header value to before the authorization value calculation. This fixes https://github.com/swift-aws/aws-sdk-swift/issues/151

Add x-amz-security-token header before calling authorization()

---

Sources/AWSSDKSwiftCore/AWSClient.swift

STS.AssumeRole() returns a credential structure, which contains a sessionToken. There is currently no way to initialize an AWS service with this sessionToken. 
This PR is the starting point of changing that. I have added a new AWSRequest.init() which takes a Credential structure as a parameter. The original initializer now creates a Credential structure and passes it onto the new initializer. Once this is in I can change the CodeGenerator to output code to create services taking a Credential structure.

Add AWSClient.init() which takes a Credential parameter

---

Sources/AWSSDKSwiftCore/Encoder/DictionaryEncoder.swift

Previously if we were expecting an array and didn't get an array we would throw an error. This change will place the object we found inside an array and process that.
This fixes an issue in apigateway https://github.com/swift-aws/aws-sdk-swift/issues/33 where single values can be returned even though we are expecting an array. Not totally sure about this change, as it is slightly weird. Although it shouldn't break anything as it is just giving the decoder another chance to decode the response, when it fails because it didn't find an array.

DictionaryDecoder: change how we deal with expecting an array

---

Package.swift
Sources/AWSSDKSwiftCore/HMAC.swift
Sources/CAWSSDKOpenSSL/include/c_awssdk_openssl.h
Sources/CAWSSDKOpenSSL/shims.c

Get aws-sdk-swift working with OpenSSL 1.1 without breaking earlier versions of OpenSSL.
Added CAWSSDKOpenSSL target to shim over differences in OpenSSL versions, specifically how HMAC contexts are created.
This is only needed for versions of the library that use nio 1.4 or less as nio2.0 includes BoringSSL with it.
@Yasumoto this is from the conversation on discord #aws this morning/yesterday

OpenSSL 1.1

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape.swift

This PR includes the core requirements for https://github.com/swift-aws/aws-sdk-swift/pull/155
- It adds a validate() function to AWSShape. By default this is an empty function. 
- Also there are general purpose validate functions that validate against max and min values and pattern match strings.
- A idempotencyToken() function has been added for automatic generation of these tokens

Add validation code to AWSShape

---

Sources/AWSSDKSwiftCore/Doc/AWSShape.swift

Check a match can be found in pattern validation, not that the whole string matches the pattern.
It appears some services expect this eg MediaConvert. Unfortunately this makes the validation slightly less rigourous for other services. We still expect the pattern to be anchored to the start of the string, so maybe this won't be too much of a change.

Check a match can be found in pattern validation

---

Package.resolved
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Sources/AWSSDKSwiftCore/Message/Body.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Store processed status code, body and headers in a single object. 
- Tidys up code
- Allows us to send a full response to AWSServiceMiddleware
- Also can start to think about processing HAL in a Future if we have a single processed response object to pass around

Encapsulate processed Response in AWSResponse struct

---

Sources/AWSSDKSwiftCore/AWSShapes/TimeStamp.swift
Tests/AWSSDKSwiftCoreTests/TimeStampTests.swift

Added a HTTP date format DateFormatter (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1). Used by most dates found in response headers
Added parsing of UNIX epoch seconds (number of seconds since 1st Jan 1970).
Added tests for parsing both of these

Add additional methods for parsing timestamps

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

If an XML Response has a payload then create a parent xml node to hold it and send that to the decoder.
This is needed to fix a bunch of CloudFront issues

Deal with XML Responses with a payload

---

Sources/AWSSDKSwiftCore/AWSClient.swift

Clean up code path to generating signed URLs. See https://github.com/swift-aws/aws-sdk-swift/issues/73
```
let s3 = S3(.euwest1)
let url = "https://mybucket.s3.amazonaws.com/key/for/my/file"
let signedURL = s3.client.signURL(url: url, httpMethod: "GET")
```

Add public facing signURL() function to AWSClient

---

Sources/AWSSDKSwiftCore/Error.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Ensuring this will simplify debugging of systems, especially on remote system
```
do {
// aws code
} catch {
print(error.localizedDescription)
} 
```
Previously code above would print out name of error class, plus error index on Mac and on Linux would print "The operation could not be completed". With this change it now prints the errorCodeString and the associated Message. 
This requires that all aws-sdk-swift services support AWSErrorType.description.

AWSErrorType conforms with CustomStringConvertible

---

Sources/AWSSDKSwiftCore/AWSClient.swift

This will simplify using the library a little

AWSClient.send() functions don't throw errors so don't mark them as if they do

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTPClient.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift

- Moved the HTTP request setup into a HTTPClientRequestSerializer class and out of ClientBootstrap code. Similar to how other http clients are doing. Its looks much cleaner.
- HTTPClient.init() no longer needs the host details. Although we don't do this, could allow us to re-use the same HTTPClient for multiple calls.
- Implemented EventLoopGroupProvider enum and initialise HTTPClient with one.
- Use AWSClient.eventGroup in HTTPClient

HTTPClient changes

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Sources/AWSSDKSwiftCore/Signers/V4.swift
Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift
Tests/AWSSDKSwiftCoreTests/SignersV4Tests.swift

CognitoIdentity and CognitoIdentityProvider can be used without authentication details. These changes allow for this to happen. 
- In AWSClient.init() If accessKeyId and secretAccessKey are nil create an expired credential.
- Metadata service is only used when credentials have expired
- Don't sign requests with empty credentials
- This means you can initialize AWSClient with accessKeyId: "", secretAccessKey: "" and avoid asking for EC2/ECS credentials and not sign requests
- CognitoIdentityProvider works without signed credentials
- Removed invalid signing test

Provide a path for initialising a service without credentials

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

We still control the usage of these methods when protected with internal, and this removes extra code during debug vs. release builds
Let's fixup https://github.com/swift-aws/aws-sdk-swift-core/issues/43

Remove the debugValidate and debugCreateAWSRequest

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Sources/AWSSDKSwiftCore/Signers/V4.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift

@jonnymacs as we discussed
- Get rid of enum
- Replace with protocol MetaDataServiceProvider. Each service conforms to this protocol
- Cleaned up decode code to use separate structure for each service.
Tested on EC2 and ECS

Refactor Metadata service

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTPClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

PR for issue #137
In order to check if anything else was using `AWSClient.eventGroup` I deprecated `eventGroup`:
```swift
@available(*, deprecated, message: "Consumers of this API shoud provide their own runtime at the initialization of an AWSClient with the EventLoopGroupProvider.use(eventLoopGroup) option.")
public static let eventGroup: EventLoopGroup = _eventGroup
private static let _eventGroup: EventLoopGroup = createEventLoopGroup()
```
This made me aware that `AWSClient.eventGroup` was also used in `Signers.V4` and `MetaDataService`. Therefore I had to dig deeper to change those APIs. I did so by dependency injection from `AWSClient`. Sadly those are breaking API changes (at least for Signers.V4 since this is a public class). It is to be discussed how many consumers use …

Added an option to inject the EventLoopGroup into the AWSClient.

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

- `AWSClient`’s static shared instance of `eventLoopGroup` is now private.
- `AWSClient`’s initialiser does not have a default property for `EventLoopGroupProvider` anymore.

Adjustments as discussed in PR #139

---

Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
Tests/AWSSDKSwiftCoreTests/SerializersTests.swift

Needed to change XMLDecoder() to work with XML.Node instead of XML.Element internally.
This fixed #149

Allow xml decoder to decode attributes as members

---

Sources/AWSSDKSwiftCore/AWSClient.swift

If a GET request has headers sign the request with an authorization header. If we don't do this AWS complains that the headers are not signed.
Fixes issue sending s3.getObjectAcl() request.

If GET request has a header then sign request using headers

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTPClient.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift

- HTTPClient has to be provided with an eventLoopGroup. It cannot create its own. Therefore does not need a close() function
- Use the static AWSClient.eventGroup in HTTPClient
This fixes the metadataservice hangs being experienced just now
We could extend this to be similar to the eventLoopGroupProvider changes in v4.x, but that would need considerable more changes on the aws-sdk-swift side as well

Use AWSClient.eventLoopGroup in HTTPClient (merge into v3.x)

---

Sources/AWSSDKSwiftCore/AWSShapes/TimeStamp.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

Added tests to measure various sections of aws-sdk-swift-core. Tests are split into three sections, create aws request, sign request and validate response.
With these I found we were wasting time creating a date formatter every time we processed a timestamp. Also found the unnecessary adding of `` around keywords, which was really expensive and then also breaking requests with swift keywords #158

Performance tests

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Encoder/DictionaryEncoder.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/DictionaryEncoderTests.swift

- Base64 is the standard decode/encode strategy for the json and xml encoders.
- The situation where we construct a dictionary with a `Foundation.Data` to be decoded later in `validate<Output: AWSShape>` https://github.com/swift-aws/aws-sdk-swift-core/blob/61ac3f1dea83a642154c1b02c1910363a9d0943b/Sources/AWSSDKSwiftCore/AWSClient.swift#L621 is a special case and shouldn't be considered the default.
- This should fix the situation where creating a dictionary to extract the payload from (in `CreateAWSRequest`). The serialization of this payload using `JSONSerialization.data(withJSONObject:)` would crash because it has been provided a dictionary containing a `Foundation.Data` object. Added test `testDataInJsonPayload` to demostrate this. Revert `DictionaryEncoder.dataEncodingStrategy` to …

Default DictionaryEncoder/Decoder to use base64

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift

Removed the eventLoopGroupProvider enum and ability for client to create its own EventLoopGroup.
Merging this change into async-http-client

NIOTSHTTPClient can only be initialised with a NIOTSEventLoopGroup

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/String.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

It appears we have been adding `` around keywords when accessing their values using `Mirror`. This doesn't work. The code seems to be left over from the Code Generator where it is needed. This PR removes this. 
Added tests to verify this.

toSwiftVariableCase() shouldn't be adding `` to variable names in the runtime.

---

Package.swift

Since we use the new `NIOAtomic` syntax introduced with SwiftNIO 2.11.0 we need to minor version bump our dependency.
PR that introduced new syntax: https://github.com/apple/swift-nio/pull/1263
cc: @weissi is such a move okay?

SwiftNIO dependency minor version bump

---

Dockerfile
Package.swift
Sources/AWSSDKSwiftCore/AWSClient+Paginate.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift
Tests/AWSSDKSwiftCoreTests/TestServer.swift
Tests/LinuxMain.swift

This is the core routine for paginating results. It uses `Mirror` to extract the results and a continuation token to get the remaining results. The code generation PR can be found here https://github.com/swift-aws/aws-sdk-swift/pull/227
At the moment to create a new request with the new continuation token I have had to create a protocol which requires a new initialiser which take the original request and a token. The initialiser should copy the contents of the original request but with the new token.
The code below demonstrates the extension for S3.ListObjectsV2 and the paginate function used to get the data.
```
extension S3.ListObjectsV2Request: AWSPaginateable {
public init(_ original: S3.ListObjectsV2Request, token: String) {
self.init(
bucket: original.bucket, 
continuationToken: …
```

Paginated results

---

Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
Sources/AWSSDKSwiftCore/Encoder/XMLEncoder.swift
Tests/AWSSDKSwiftCoreTests/JSONCoderTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift
Tests/AWSSDKSwiftCoreTests/SerializersTests.swift
Tests/AWSSDKSwiftCoreTests/XMLCoderTests.swift
Tests/LinuxMain.swift

Found this while implementing the QueryEncoder.
The container coding was not being reset in the UKEC encode/decode encode<T>(_) functions so the container coding was being applied to the child elements of the array. This only caused an issue when encoding/decoding dictionaries where the key was not a base type eg an enum and the value was a Codable type. The container coding for the UKEC was being passed to the KEC that coded the Codable type.

Fixed Dictionary<enum, object> in XMLEncoder/XMLDecoder plus optimization

---

Package.swift
Sources/AWSSDKSwiftCore/AWSClient+HAL.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

We aren't interested in the majority of hal+json output. The only things we need are the resources. Resources can be included as normal, or they can be included inside an "_embedded" tag. Instead of running the HAL code I just look for the "_embedded" tag and if it exists merge everything underneath with the top level json dictionary and output that.

Remove HypertextApplicationLanguage framework

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

The AWSClient encapsulates *a lot* of functionality. For this reason it is in the interest of the maintainers to distribute functionality to the objects it belongs to.
I moved the conceptionally static method `createHTTPRequest` from the AWSClient to AWSRequest where it is a great fit as an instance method.
Less Code on AWSClient. Clearer encapsulation of functionality on AWSRequest.

Moved `toHTTPRequest()` from AWSClient to AWSRequest.

---

Sources/AWSSDKSwiftCore/Encoder/AWSShapeEncoder.swift
Sources/AWSSDKSwiftCore/Error.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Previously XML namespaces only ever set when they were attached to Payload objects. This change fixes the situation where the XML namespace is for the parent AWSShape and not the payload object.

Set XML namespace in AWSShapeEncoder

---

Sources/AWSSDKSwiftCore/Signers/V4.swift

signedHeaders() sorted after lowercased was applied, canonicalHeaders() sorted before lowercased was applied.

Fixed error in header sorting

---

Sources/AWSSDKSwiftCore/AWSClient.swift

- If restjson service cannot find error code in "x-amzn-ErrorType" header check response body
- Process EC2 errors so we return error codes

Error handling for restjson and EC2

---

Sources/AWSSDKSwiftCore/Encoder/AWSShapeEncoder.swift
Tests/AWSSDKSwiftCoreTests/QueryEncoderTests.swift

Hi, there
The email subject is empty when I send raw email via [SES.sendRawEmail](https://github.com/swift-aws/aws-sdk-swift/blob/4.x.x/Sources/AWSSDKSwift/Services/SES/SES_API.swift#L294), because the request body "RawMessage.Data" is like "xx bytes".
This PR make a AWSShape same as [SES.RawMessage](https://github.com/swift-aws/aws-sdk-swift/blob/4.x.x/Sources/AWSSDKSwift/Services/SES/SES_Shapes.swift#L2199), and tested it.
Please review it. thank you.

Fix QueryEncoder for Data blob AWSShapeMember

---

Sources/AWSSDKSwiftCore/Encoder/QueryEncoder.swift
Tests/AWSSDKSwiftCoreTests/QueryEncoderTests.swift

The query encoder should encode `Foundation.Data` as base64

Query encoder and Data

---

Sources/AWSSDKSwiftCore/Encoder/DictionaryEncoder.swift
Tests/AWSSDKSwiftCoreTests/DictionaryEncoderTests.swift

The test for whether `_DictionaryEncoder.box(_ dict: [String: Encodable])` is called is causing a warning in swift 5.2. I have removed this test plus the code it calls. Also removed equivalent decoder version for consistency.
I'm not sure why the JSONEncoder/Decoder (where we got this code from) has special code in place for `[String: Encodable]` as there are correct versions of this already implemented in `Dictionary.encode()` already.

Swift 5.2 warning and DictionaryEncoder

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Encoder/DictionaryDecoder.swift
Sources/AWSSDKSwiftCore/Encoder/QueryEncoder.swift
Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
Sources/AWSSDKSwiftCore/Encoder/XMLEncoder.swift
Sources/AWSSDKSwiftCore/Message/AWSMiddleware.swift
Sources/AWSSDKSwiftCore/XML.swift

- Removed `public` from the encoders
- Removed `URL.hostWithPost` as it is unnecessary
- `XML` is now an `enum`
- `AWSLoggingMiddleware` is now a `struct`

Remove unnecessary public symbols

---

Sources/AWSSDKSwiftCore/AWSClient+Paginate.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift

Associated PR in aws-sdk-swift is https://github.com/swift-aws/aws-sdk-swift/pull/263
Replace `AWSPaginateStringToken` and `AWSPaginateIntToken` with `AWSPaginateToken` which has an associated type `Token`. This allows us to generalize all the paginate code and allow for tokens that are not strings or integers.

Paginate token with associated type

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape+Encoder.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape.swift
Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/DictionaryEncoderTests.swift
Tests/AWSSDKSwiftCoreTests/JSONCoderTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift
Tests/AWSSDKSwiftCoreTests/QueryEncoderTests.swift
Tests/AWSSDKSwiftCoreTests/TestServer.swift
Tests/AWSSDKSwiftCoreTests/ValidationTests.swift
Tests/AWSSDKSwiftCoreTests/XMLCoderTests.swift

You can find the associated aws-sdk-swift PR [here](https://github.com/swift-aws/aws-sdk-swift/pull/253).
This means we don't generate unnecessary codable code. Requests only need to be encodable and responses only need to be decodable.
This also allows us to remove coding keys for header, query and uri variables for requests as they are not needed for the encode (decode requires them).

Split AWSShape into AWSEncodableShape and AWSDecodableShape

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/AWSShapes/Payload.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape.swift
Sources/AWSSDKSwiftCore/Message/Body.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Tests/AWSSDKSwiftCoreTests/QueryEncoderTests.swift
Tests/AWSSDKSwiftCoreTests/TestServer.swift

Associated PR in aws-sdk-swift is https://github.com/swift-aws/aws-sdk-swift/pull/257
Add a `AWSPayload` object for data blob payloads in requests. The internal representation is ByteBuffer but allow it to be initialised with `Data`, `ByteBuffer` or `String`. While the user still has the ability to create a payload from a `Data` object as before, they can also supply a `ByteBuffer` which they may have received from another process eg `NIONonBlockingFileIO`.
NB This also removes `Body.init(anyValue: Any)`

Payload Object

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/Region.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Allow users to provide an arbituary region name using enum case Region.other(String). See #226
This has meant we have had to add our own version of `init(rawValue)` and `rawValue`.

Added possibility of arbituary named regions

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/RetryController.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/TestServer.swift

Add support for retrying requests when they fail. Give users complete control over how the client responds to a failed request.
- Added RetryController protocol with one function which returns a retryWaitTime or nil depending on whether the failed request should retry.
- Created NoRetry, ExponentialRetry and JitterRetry versions of RetryController
- Removed status code error processing from validate functions
- If status code is not 2xx then throw error
- Catch any errors from HTTPclient execute including errors from non 2xx status
- Send error to retryController along with attempt number.
- Retry HTTP request if it returns a retry wait time.
- Added tests for retrying after errors
- Extended AWSTestServer to have more control over when errors are thrown.

Adding support for retrying requests that fail

---

.github/workflows/ci.yml
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTP/AWSHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/AsyncHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

Equivalent aws-sdk-swift PR can be found here https://github.com/swift-aws/aws-sdk-swift/pull/250
Added `httpClientProvider` parameter to `AWSClient.init()` which takes an enum that indicates if the user wants to use the default http client or one they provide.
Removed eventLoopGroupProvider as the user can provide this via their own httpClient and supplying both an httpClient and an eventLoopGroup doesn't make sense as the only place we use the eventLoopGroup is in the httpClient.
This allows the user to provide a version of `AsyncHTTPClient` with their own configuration, an application global HTTP client, or even a custom written client as long as it conforms to `AWSHTTPClient`.

Allow user to set the HTTPClient for AWSClient

---

Sources/AWSSDKSwiftCore/AWSClient+Paginate.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/CredentialProvider.swift
Sources/AWSSDKSwiftCore/HTTP/AWSHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/AsyncHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift

Added `on eventLoop: EventLoop` parameter to send() functions and then pass this eventLoop through all the systems.
This allows users of aws-sdk-swift more control over which eventloop their requests run on.

Added `on eventLoop: EventLoop` parameter to send() functions

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/RetryController.swift
Sources/AWSSDKSwiftCore/ServiceConfig.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/TestUtils.swift

See https://github.com/swift-aws/aws-sdk-swift/issues/231 first
Based off #201 except I haven't added accessors to `AWSClient` where variables were internal. Also internally all accesses to the `ServiceConfig` are through the `serviceConfig` variable as this is how we will be accessing them when we move away from the client owning this data. 
Found a few variable we don't need to store. We only need them to construct the `endpoint` so I don't store them anymore.

ServiceConfig object defining AWS service

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/AWSShapes/Payload.swift
Sources/AWSSDKSwiftCore/Encoder/DictionaryDecoder.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift

`AWSPayload` conforms to `Decodable` so we can add it into `Decodable` responses, but the `init(from: Decoder)` should never be called. As it represents the body of a response, the only `Decoder` that will run on it is the  `DictionaryDecoder` which is used in the situations where the body is raw data. Added code to `DictionaryDecoder` to directly copy `AWSPayload` into output shape and not attempt to decode it.
Added `AWSPayload.asByteBuffer()`, `AWSPayload.asData()`, `AWSPayload.asString()` to convert to required format.

Support AWSPayload object in response

---

Sources/AWSCrypto/ByteArray.swift
Sources/AWSCrypto/Digest.swift
Sources/AWSCrypto/HMAC.swift
Sources/AWSCrypto/HashFunction.swift
Sources/AWSCrypto/Insecure.swift
Sources/AWSCrypto/MD5.swift
Sources/AWSCrypto/SHA2.swift
Sources/AWSCrypto/SymmetricKey.swift
Sources/AWSCrypto/exports.swift

Another package may have a Crypto dependency which will mess with this check

Don't check if we can import Crypto, check for linux

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape+Encoder.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape.swift
Sources/AWSSDKSwiftCore/Encoder/DictionaryDecoder.swift
Sources/AWSSDKSwiftCore/Encoder/QueryEncoder.swift
Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
Sources/AWSSDKSwiftCore/Encoder/XMLEncoder.swift
Tests/AWSSDKSwiftCoreTests/DictionaryEncoderTests.swift
Tests/AWSSDKSwiftCoreTests/XMLCoderTests.swift

Removed unnecessary code from `DictionaryDecoder`, `XMLEncoder` and `XMLDecoder`
removed encoder/decode NS Foundation objects. 
removed dateEncoding/Decoding strategy's as this is dealt with by TimeStamp
removed encode/decode URLs
removed some of the Data encoder strategies
removed `flattenContainers` from `QueryEncoder`

Remove unused/unnecessary code from the Encoders/Decoders

---

Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
Tests/AWSSDKSwiftCoreTests/XMLCoderTests.swift

Previously all arrays decoded from XML had to be optional otherwise they would fail to decode if there wasn't any members. I have moved the CodingKey exists test into container and unkeyedContainer methods to avoid the decoder throwing an error on a non-existent array member. Now empty arrays decode.

Fix decoding of empty XML arrays

---

Sources/AWSSDKSwiftCore/AWSShapes/TimeStamp.swift
Sources/AWSSDKSwiftCore/Encoder/CodableProperties/TimeStampCoder.swift
Tests/AWSSDKSwiftCoreTests/TimeStampTests.swift

Previously TimeStamp would load one of three formats: ISO8601, HTTP header and Unix Epoch. It would only ever output one format: ISO8601
This change, add a TimeStampCoder that will encode to a specified format and decode from a specified format.

Add TimeStampCoders to enforce timestamp format

---

Package.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/ServiceConfig.swift

Using swift-metrics
Metrics also record AWS service and operation
I've verified this works using SwiftPrometheus

Implement RED metrics recording

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape+Encoder.swift
Sources/AWSSDKSwiftCore/Encoder/QueryEncoder.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/QueryEncoderTests.swift

Add code to capitalize query variables when outputting for EC2
Can't do this in the shapes as some of the same shapes are used in response generation and sometimes in that situation the variables are required to be lowercase.

Add specialization for EC2 Query generation

---

.github/workflows/ci.yml

We say we support it so we should test it.
It shows a whole load of warnings compiling CNIOBoringSSL, but iOS never uses CNIOBoringSSL so shouldnt be an issue.

Add testing iOS build to CI

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/AWSShapes/Payload.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape.swift
Sources/AWSSDKSwiftCore/HTTP/AWSHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/AsyncHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
Sources/AWSSDKSwiftCore/Message/AWSMiddleware.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Sources/AWSSDKSwiftCore/Message/Body.swift
Sources/AWSSDKSwiftCore/MetaDataService.swift
Sources/AWSSignerV4/signer.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
Tests/AWSSDKSwiftCoreTests/TestServer.swift
Tests/AWSSDKSwiftCoreTests/TestUtils.swift

AWSPayload is now an enum and has a `.stream` case which has parameters `size` and `closure`. `closure` supplies `EventLoopFuture<ByteBuffer>`. It is repeatedly called until enough data has been supplied.
Internally `Body.buffer` is now `Body.raw` and has a AWSPayload as a parameter. As with the streaming response PR this functionality is only available with AsyncHTTPClient.
TODO:

Add support for streaming request payload

---

Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

- Always sign requests by adding header fields instead of signing the url
- Added a test to check that a signed header is used

Always sign request by adding Header fields

---

.github/workflows/sanity.yml
scripts/sanity.sh

Remove .build from exceptions as it is ignored later
Run on Ubuntu
Add additional call to head so only first so many lines are checked

Sanity.sh updates

---

Sources/AWSSDKSwiftCore/AWSClient.swift

Found adding a '/' to a query parameter broke signing. Lookup documentation to find the list of allowed characters. 
Don't know why I haven't hit this before.

Edited query allowed characters to be in line with AWS docs

---

Sources/AWSXML/XML.swift

`components` returns a `String` array, while `split` returns a `Substring` array

Replace String.components call with String.split

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Errors/Error.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Previously if we were supplied with an error that is not in the expected format, we would throw an error about parsing the file, with no indication we have received an error back from AWS.
This change will throw an AWSError, with status code, message "Unhandled error" and message body

Deal with unparsable errors better

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape+Encoder.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Sources/AWSSDKSwiftCore/Message/Body.swift
Sources/AWSTestUtils/TestServer.swift

It causes warning "'AWSXML' inconsistently imported as implementation-only".
It is undefined what is happening here, so I'm removing it.

Remove @_implementationOnly import of AWSXML

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/CredentialProvider.swift
Sources/AWSSDKSwiftCore/Credential/RotatingCredentialProvider.swift
Sources/AWSSDKSwiftCore/Credential/RuntimeCredentialProvider.swift
Sources/AWSTestUtils/TestServer.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift
Tests/AWSSDKSwiftCoreTests/TimeStampTests.swift
docker/docker-compose.yml

Required to call this before an AWSClient is deleted
Cleans up any credential provider processes
Shutsdown HTTPClient if owned by AWSClient

Added AWSClient.syncShutdown()

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/HTTP/AWSHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/AsyncHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/ResponseDelegate.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Sources/AWSTestUtils/TestServer.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

The sibling PR for this is https://github.com/swift-aws/aws-sdk-swift/pull/268
This is only supported for AsyncHTTPClient. I would need to restructure `NIOTSHTTPClient` a fair bit to support it and when NIOTS is supported by AsyncHTTPClient we we will be ditching `NIOTSHTTPClient`. So I'm not gonna waste my time.
Some commands eg `S3.getObject()` stream the payload in their response. This PR is to support this.
- Created a `AWSHTTPClientResponseDelegate` to process the response coming from `HTTPClient`. Send body `ByteBuffers` to a `stream` closure supplied at initialisation of `AWSHTTPClientResponseDelegate`.
- Added new `AWSClient.send` method which takes a `stream` closure.
- Added `AWSClientTests.testStreamingResponse` for testing of streaming a `ByteBuffer`

Support for streaming response payload

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Doc/AWSMemberEncoding.swift
Sources/AWSSDKSwiftCore/Doc/AWSShape.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

Removed `AWSShapeEncoding.encoding`. It was only ever used for raw payloads.
Added `PayloadOptions.raw` for raw payloads
Also rename payloadPath to _payloadPath and options to _payloadOptions to avoid name clashes

Remove AWSMemberEncoding.encoding, add payload flag raw

---

Sources/AWSSDKSwiftCore/Message/AWSMiddleware.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse+HAL.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/AWSRequestTests.swift

Also
- remove unused initialiser for `AWSRequest`
- apply content-type and user-agent headers at initialisation
- add support for encoding headers that are dictionaries. Uses pattern set by s3 `x-amz-meta-` headers.
I couldn't do the same for `AWSResponse` as it would have broken the decoding the `x-amz-meta-` headers. Will need to find another way to do this. But I did lowercase all the header names in AWSResponse so we get a consistent casing for response headers.

AWSRequest uses HTTPHeaders instead of dictionary

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/CredentialProvider.swift
Sources/AWSSDKSwiftCore/Credential/CredentialProviderError.swift
Sources/AWSSDKSwiftCore/Credential/NullCredentialProvider.swift
Sources/AWSSDKSwiftCore/Credential/StaticCredential+Environment.swift

This shall offer an alternative approach to #302.
We might think about wrapping the eventLoop and the httpClient into a Context object, to make breaking changes less likely. @adam-fowler wdyt?

CredentialProviderFactory with dot notation

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/AWSServiceConfig.swift
Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Sources/AWSTestUtils/TestUtils.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

This reduces the impact of #276
- rename `ServiceConfig` to `AWSServiceConfig` to prevent symbol clashes with other libraries
- remove `serviceConfig` property from `AWSClient` and the corresponding public accessor properties
- rename all `AWSClient.send` methods to `AWSClient.execute`
- `AWSServiceConfig` must now be provided individually to any of the `AWSClient.execute` methods
- the computed `signer` property on `AWSClient` is now a function (also needs the config)
- adjusted the tests
- the `aws-sdk-swift` package still needs to be adjusted to reflect these changes
- concerning the `AWSClient.createSigner` method: should we really require an `AWSServiceConfig` or is it ok to just provide `signingName` and `region` individually (possibly overloading with a method that still takes the …

Refactor ServiceConfig

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/CredentialProvider.swift
Sources/AWSTestUtils/TestUtils.swift

Can we keep the parameter name as `credentialProvider`. No one is going to thank us for the extra 7 letters. 
Also can we keep the parameter as an optional. 
1) the default provider is part of the public function signature so we can't change it
2) eventually `runtime` is being replaced with `group` containing a list of providers, which changes per platform, which as a default parameter will be a pain, also we wouldnt be able to change that list with going up a major version.

AWSClient.init credentialProvider parameter changes

---

Sources/AWSSDKSwiftCore/AWSShapes/Payload.swift
Sources/AWSSDKSwiftCore/HTTP/S3StreamReader.swift
Sources/AWSSDKSwiftCore/HTTP/StreamReader.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Instead of outputting a `ByteBuffer` stream functions now return `StreamReaderResult`. This can be either a `.byteBuffer(ByteBuffer)` or a `.end`. The `.end` replaces returning an empty ByteBuffer to indicate there is no more data.

Stream function return StreamReaderResult

---

Sources/AWSSDKSwiftCore/Credential/DeferredCredentialProvider.swift
Sources/AWSSDKSwiftCore/Credential/RotatingCredentialProvider.swift

- Added syncShutdown() call to managed CredentialProvider in both RotatingCredentialProvider and DeferredCredentialProvider. 
- Also fixed hang, where the RotatingCredentialProvider.syncShutdown wouldn't finish because it was waiting on a EventLoopFuture to complete but the EventLoopFuture couldn't finish because it couldn't get access to the lock that syncShutdown had locked

Provider sync shutdown

---

Sources/AWSSDKSwiftCore/Credential/MetaDataCredentialProvider.swift
Sources/AWSTestUtils/TestServer.swift
Tests/AWSSDKSwiftCoreTests/Credential/MetaDataCredentialProviderTests.swift
Tests/AWSSDKSwiftCoreTests/Credential/RotatingCredentialProviderTests.swift
Tests/AWSSDKSwiftCoreTests/Credential/RuntimeSelectorCredentialProviderTests.swift
docker/docker-compose.yml

Added fake ec2/ecs metadata servers in AWSTestUtils to test acquiring of EC2/ECS credentials

Fake ec2/ecs metadata servers in AWSTestUtils

---

Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/RetryPolicy.swift
Sources/AWSTestUtils/TestUtils.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift

Setup like the credential provider factory, for consistency
Instead of calling 
```
let client = AWSClient(retryPolicy: JitterRetry())
```
now the user calls
```
let client = AWSClient(retryPolicy: .jitter())
```
Dot notation eases finding retry policies
removes a load of public symbols

Added RetryPolicyFactory struct with dot notation

---

Sources/AWSTestUtils/TestServer.swift

Set "Content-Length" header in Response, that AWSTestServer returns

AWSTestServer "Content_Length" header fix

---

Sources/AWSTestUtils/TestServer.swift

Finally worked out it doesnt like "Content-Length" header in response

Fix random AWSTestServer crashes

---

Package.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/Credential/CredentialProviderError.swift
Sources/AWSSDKSwiftCore/Credential/MetaDataCredentialProvider.swift
Sources/AWSSDKSwiftCore/HTTP/AWSHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/AsyncHTTPClient.swift
Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
Sources/AWSSDKSwiftCore/Message/AWSResponse.swift
Sources/AWSTestUtils/TestUtils.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/AWSResponseTests.swift
Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
Tests/AWSSDKSwiftCoreTests/LoggingTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

Using swift-log
Logs: requests, responses, errors, retries
passes Logger to AWSHTTPClient to be passed to AsyncHTTPClient when 1.2.0 released.
Will look to merge in credential provider logging support later on, wanted to simplify the initial PR.

Add logging to AWSClient

---

Sources/AWSSDKSwiftCore/AWSShapes/Payload.swift
Sources/AWSSDKSwiftCore/HTTP/StreamReader.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift

Returns with how much data has been uploaded so far
User can throw an error from callback to cancel upload

Add callback to AWSPayload.fileHandle

---

Sources/AWSSDKSwiftCore/AWSClient+Paginate.swift
Sources/AWSSDKSwiftCore/AWSClient.swift
Sources/AWSSDKSwiftCore/AWSService.swift
Sources/AWSSDKSwiftCore/AWSServiceConfig.swift
Sources/AWSSDKSwiftCore/AWSServiceContext.swift
Sources/AWSTestUtils/TestUtils.swift
Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Tests/AWSSDKSwiftCoreTests/AWSServiceTests.swift
Tests/AWSSDKSwiftCoreTests/LoggingTests.swift
Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift

Create `AWSServiceContext` struct that holds context data for requests
AWSClient public functions take `AWSServiceContext` in addition to the `AWSServiceConfig`
Added `AWSService` protocol that supports editing of `AWSServiceContext`

AWSServiceContext version 2

---

Sources/AWSSDKSwiftCore/Credential/DeferredCredentialProvider.swift

internalCredential can be in the process of being set when it is accessed

Fix bug with DeferredCredentialProvider.credential access

---

Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
scripts/sanity.sh

As discussed, here is a new PR to address https://github.com/soto-project/soto-core/issues/359
The proposed solution to handle Linux and macOS by just changing [this line](https://github.com/soto-project/soto-core/blob/main/Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift#L116) does not work, because when running in a sandboxed app `wexp.we_wordv` is nil.
I revert back to my original solution. Tested on macOS Catalina on both a sanboxed (with appropriate entitlements for file access) and not sandboxed app.

macOS tilde expansion in path for sandboxed app

---

Sources/SotoCore/Encoder/CodableProperties/TimeStampCoder.swift
Tests/SotoCoreTests/TimeStampTests.swift

Add additional format for ISO8601TimeStampCoder
This fixes issue with ApiGatewayV2 decoding iso8601 TimeStamps without milliseconds

Allow for multiple timestamp formats in TimeStampFormatCoder

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/AWSService.swift
Sources/SotoCore/Exports.swift
Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

Allow user to include headers in signed URL.
When the url is used the same headers will need to be supplied to the http client.

Sign URL with headers

---

Sources/SotoCore/Message/AWSResponse.swift
Tests/SotoCoreTests/AWSResponseTests.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

restjson errors can come in the form 
```
{"message": "there has been a message"}
```
or 
```
{"Message": "there has been a message"}
```
The inconsistent capitalization was meaning the second version wasn't been parsed. This change checks for both

Rest json error parsing fix

---

Sources/AWSSDKSwiftCore/MetaDataService.swift

When the InstanceMetaDataServiceProvider requests credentials for
the instance role, the URI contained two subsequent "//" slashes.
This resulted in a `MOVED PERMANENTLY` redirect which was not
followed, and thus failing the request.

Removes duplicate "/" in InstanceMetaDataServiceProvider request

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/AWSService.swift
Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

Also changed this to a `TimeAmount` instead of an `Int`. Makes for easier reading
```
let url = signer.signURL(
url: URL(string: "https://test-bucket.s3.amazonaws.com/test-put.txt")!, 
method: .GET, 
expires: .minutes(30)
)
```

signURL parameter expires no longer has a default

---

Sources/SotoCore/Encoder/CodableProperties/CodableProperties.swift
Sources/SotoCore/Encoder/CodableProperties/CollectionCoders.swift
Tests/SotoCoreTests/QueryEncoderTests.swift
Tests/SotoCoreTests/TimeStampTests.swift
Tests/SotoXMLTests/XMLCoderTests.swift

Rename `Coding` property wrapper to `CustomCoding`. Coding is too generic a name for a public symbol.

Coding to CustomCoding

---

Sources/SotoCore/AWSService.swift
Sources/SotoCore/AWSServiceConfig.swift
Tests/SotoCoreTests/AWSServiceTests.swift

AWSService.with(middlewares:timeout:byteBufferAllocator:options) returns a new version of the AWSService with edited attributes

Create new AWSService with updated serviceConfig values

---

Sources/SotoCore/Doc/AWSShape+Encoder.swift
Sources/SotoCore/Encoder/QueryEncoder.swift
Sources/SotoCore/Message/AWSRequest.swift
Sources/SotoXML/XMLDecoder.swift
Sources/SotoXML/XMLEncoder.swift
Tests/SotoCoreTests/QueryEncoderTests.swift

Looking to improve performance by removing temporary dictionary containing query keys and values. QueryEncoder now generates the query string and manages the encoding of the query keys. Haven't completely removed temporary dictionary as I need to sort the query values by key, but changed this to an array of (key, value) tuples. This is all internal to QueryEncoder now so allows us to spend more time on optimising this.
To allow QueryEncoder to output final string, added additional keys to prime the encoder with (add "Action" and "Version" fields with this). Also verified there are no query based GET operations that have a body so can remove the test for this.

Query encoder cleanup/performance improvement

---

Sources/SotoCore/AWSClient+Paginate.swift
Tests/SotoCoreTests/PaginateTests.swift

A lot of the time paginate fuctions are going to be used in the following way
```
var files: [String] = []
_ = try listFilesPaginator(input) { response, eventLoop in
files.append(response.files)
return eventLoop.makeSucceededFuture(true)
}.wait()
```
This change allows you to do the following which is cleaner
```
let files = try listFilesPaginator(input, []) { current, response, eventLoop in
return eventLoop.makeSucceededFuture((true, current + response.files))
}.wait() 
```
I also re-implemented the original functions using new `reduce` style functions

Add Array.reduce style paginate function.

---

Sources/SotoCore/Errors/Error.swift
Sources/SotoCore/Message/AWSResponse.swift
Tests/SotoCoreTests/AWSResponseTests.swift

Parse errors for additional fields we don't know about and place them in a `additionalFields: [String: String]` member of `AWSErrorContext`

Add additional fields to AWSErrorContext

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/RetryPolicy.swift

This means we can make retry decisions based on a `AWSErrorType` instead of a raw HTTP Response error

Process AWS Errors before called RetryPolicy.getRetryWaitTime

---

Sources/SotoCore/AWSClient+Paginate.swift
Sources/SotoCore/AWSClient.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/PaginateTests.swift

Re-order Logger and EventLoop parameters in public functions of AWSClient so it is easier to replace Logger with BaggageContext at a later date

Logger Eventloop parameter ordering

---

Sources/SotoCore/HTTP/S3StreamReader.swift
Tests/SotoCoreTests/AWSClientTests.swift

Stop streamer sending buffers that are too large when it is fed bytebuffers greater than the chunk buffer size (64KB)

Fix issue with S3 streamer

---

Sources/SotoCore/Credential/STSAssumeRole.swift
Tests/SotoCoreTests/Credential/STSAssumeRoleTests.swift

Was providing it with a credential that had expired. Thus when we called `getCredential(` it would try to call stsAssumeRole again

Fix testInternalSTSAssumeRoleProvider

---

Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift
Sources/SotoCore/Credential/ConfigFileLoader.swift
Sources/SotoCore/Credential/CredentialProviderError.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Tests/SotoCoreTests/Credential/ConfigFileLoaderTests.swift

Removed enum case `credentialSource` instead use `assumeRole` for both source_profile and credential_source. Instead of it holding a `StaticCredential` it now holds a `CredentialProviderFactory`. In the situation we are dealing with source_profile this is set to `.static()`. For `credential_source` we use one of `.environment`, `.ec2`, `.ecs`.
Add test, testing with environment credential

Support credential_source in config file

---

.github/workflows/ci.yml
Sources/SotoCore/AWSClient.swift
Sources/SotoCore/AWSService.swift
Sources/SotoCore/Message/AWSRequest.swift
Sources/SotoSignerV4/signer.swift
Tests/SotoCoreTests/AWSRequestTests.swift
Tests/SotoCoreTests/AWSServiceTests.swift
Tests/SotoCoreTests/Credential/STSAssumeRoleTests.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

See https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html for details
- Percent encode paths twice if service isn't s3 
- Order query params first by key and if keys are equal then by value
- Add `AWSSigner.processURL` to clean a URL before passing to signer (use in `AWSClient.signURL`)
- Add `AWSClient.signHeaders` which returns signed headers instead of a signed URL. (useful for Elasticsearch which needs signed headers instead of a signed URL)

Fixes for the V4 Signer

---

Sources/SotoCore/Encoder/CodableProperties/CodableProperties.swift
Sources/SotoCore/Encoder/CodableProperties/DateCoders.swift
Sources/SotoCore/Message/AWSRequest.swift
Tests/SotoCoreTests/AWSRequestTests.swift

CustomEncoder protocol has new `string(from: CodableValue)` function. If you implement this then the wrapped value will be returned. Otherwise nothing will be output

Add support for output CustomCoding values in headers and querys

---

Sources/SotoCore/Encoder/DictionaryDecoder.swift
Sources/SotoCore/Message/AWSResponse.swift
Tests/SotoCoreTests/AWSResponseTests.swift

When decoding JSON we first convert to a dictionary so we can add in additional values read from the headers and then push the resultant dictionary through the dictionary decoder. We have to guess whether the value is going to be decoded as a number, boolean or string as the decoder will throw a typeMismatch error. This is not ideal. So I have added a new type which encapsulates values extracted from headers and have that be convertible to `Bool`, `NSNumber` or `String`.
Add StringFlexibleDecodable for decoding headers values added to dictionaries before decoding with the DictionaryDecoder

Add StringFlexibleDecodable for decoding headers values

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Credential/CredentialProvider.swift
Sources/SotoCore/Credential/DeferredCredentialProvider.swift
Sources/SotoCore/Credential/MetaDataCredentialProvider.swift
Sources/SotoCore/Credential/RotatingCredentialProvider.swift
Sources/SotoCore/Credential/RuntimeSelectorCredentialProvider.swift
Sources/SotoCore/Message/AWSResponse.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Tests/SotoCoreTests/Credential/ConfigFileLoaderTests.swift
Tests/SotoCoreTests/Credential/CredentialProviderTests.swift
Tests/SotoCoreTests/Credential/RotatingCredentialProviderTests.swift
Tests/SotoCoreTests/LoggingTests.swift

More logging level changes
In general downgrading or using levels set in options
- AWSResponse uses error level from AWSClient
- Metadata credential provider uses trace for logging where IMDS token is coming from
- Extend `CredentialProviderContext` to include `AWSClient.options` and use error logging level in `RuntimeSelectorCredentialProvider`

Logging level changes

---

Package.swift
Sources/SotoCore/HTTP/AsyncHTTPClient.swift
Sources/SotoCore/HTTP/ResponseDelegate.swift

Before AsyncHTTPClient v1.3.0 if you implemented your own `ResponseDelegate` the `EventLoopFuture` that `HTTPClient.execute` returns could complete before your delegate had finished processing the body parts. I had to add a hack to the `AWSClient` streaming response delegate to ensure we returned after all processing had been done by adding an additional promise to the delegate and then waiting on that promise completing before I could guarantee the delegate had done its work.
Now AHC v1.3.0 is out I can remove this hack.

Remove hack to fix issues with AHC backpressure

---

Package.swift
Sources/SotoCore/AWSClient+Paginate.swift
Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Encoder/CodableProperties/CodableProperties.swift
Sources/SotoCore/Waiters/AWSClient+Waiter.swift
Sources/SotoCore/Waiters/Matcher.swift
Tests/SotoCoreTests/WaiterTests.swift

Waiters are a client-side abstraction used to poll a resource until a desired state is reached, or until it is determined that the resource will never enter into the desired state. This is a common task when working with services that are eventually consistent like Amazon S3 or services that asynchronously create resources like Amazon EC2. Writing logic to continuously poll the status of a resource can be cumbersome and error-prone. The goal of waiters is to move this responsibility out of customer code and onto Soto.
- Added `AWSClient.waitUntil` function which polls a resource until a matcher returns a positive
- Implemented various matchers. Include path (matching value using JMESPath), error status, error code, anyPath and allPath for multiple values returned by a path
See the Smithy …

Add support for waiters using JMESPath

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Doc/AWSShape.swift
Sources/SotoCore/Message/AWSRequest.swift
Tests/SotoCoreTests/AWSRequestTests.swift

A number of services have API calls that add a prefix to the host name (chime, location, s3control etc). This PR implements this by adding an optional `hostPrefix` parameter to all the `AWSClient.execute` functions. If set it prepends this value to the hostname. It is also possible to have input shape members affect this prefix. See `S3Control` that prepends the hostname with the account number of the user.
See related Soto PR https://github.com/soto-project/soto/pull/507

Add host prefix to AWSRequest

---

Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

If `omitSecurityToken` is set to true the `x-amz-security-token` header will not be included in the V4 signature. This is required for IoT MQTT connections. The interface replicates the same interface used in the new AWS C runtime.

Add `omitSecurityToken` parameter to `AWSSigner.signHeaders()`

---

Sources/SotoCore/AWSClient+EndpointDiscovery.swift
Sources/SotoCore/AWSServiceConfig.swift
Sources/SotoCore/EndpointDiscovery.swift
Sources/SotoSignerV4/signer.swift
Tests/SotoCoreTests/EndpointDiscoveryTests.swift

DynamoDB and TimeStream both use endpoint discovery to provide endpoints to the user. For DynamoDB this is an optional feature but for TimeStream this is a requirement. This PR adds endpoint discovery internal to Soto instead of expecting the user to do this.
The code adds in five new versions of `AWSClient.execute` with additional parameter `endpointDiscovery`. This type contains storage for a cached endpoint and a closure to call to get a new endpoint. 
There are two types of endpoint acquisition: one where you are required to use the endpoint returned by endpoint discovery (TimeStream) and one where you can use the standard endpoint while endpoint discovery is in progress (DynamoDB). Both of these are supported. Given the DynamoDB calls are not dependent on the endpoint discovery to …

Add support for Endpoint discovery

---

Sources/SotoCore/AWSShapes/Payload+async.swift
Sources/SotoCore/AWSShapes/Payload.swift
Sources/SotoCore/HTTP/StreamReader.swift
Sources/SotoCore/Message/AWSRequest.swift
Tests/SotoCoreTests/AWSClientTests+async.swift

This adds AWSPayload.asyncSequence which allows you to provide an AsyncSequence of ByteBuffers to a request.
This will merge into the bigger async-await PR #431

Add AWSPayload.asyncSequence

---

Package.swift

Because of an issue with Xcode 13 GM SDK, swift-nio requires a workaround to compile (https://github.com/apple/swift-nio/issues/1955). This has been released in `2.32.3`.

Fix compile issue with swift-nio in Xcode 13 GM

---

Sources/SotoCore/Message/AWSResponse.swift
Tests/SotoCoreTests/AWSResponseTests.swift

When decoding an error returned by AWS, we attempt to extract any fields from the error that are non-standard and place them in a `Dictionary<String, String> called `additionalFields`. This ends up being not such a good idea because it assumes all additional fields will be strings. This change means if we decode an error which has a non string type additional field it will not throw an error and still create the error type expected.
This should fix https://github.com/soto-project/soto/issues/532

Don't throw errors on failure to decode additional fields of AWS error

---

Sources/SotoCore/AWSServiceConfig.swift
Sources/SotoCore/Doc/AWSMemberEncoding.swift
Sources/SotoCore/Message/AWSRequest.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/AWSRequestTests.swift
Tests/SotoCoreTests/AWSResponseTests.swift
Tests/SotoCoreTests/TimeStampTests.swift

Managed to lose this in a rebase from main to 6.x.x

Hostname encoding (resurrected)

---

Sources/SotoCore/RetryPolicy.swift
Tests/SotoCoreTests/AWSClientTests.swift

Changed testCustomRetryPolicy test as it depended on retrying on NIOConnectionError

Remove retry on NIOConnectionError as AsyncHTTPClient does this for us

---

Benchmark/Sources/soto-benchmark/AWSClientSuite.swift
Sources/SotoCore/AWSClient+EndpointDiscovery.swift
Sources/SotoCore/AWSClient.swift
Sources/SotoCore/AsyncAwaitSupport/AWSClient+EndpointDiscovery+async.swift
Sources/SotoCore/AsyncAwaitSupport/AWSClient+async.swift
Sources/SotoCore/Credential/CredentialProvider.swift
Sources/SotoCore/Credential/STSAssumeRole.swift
Sources/SotoCore/HTTP/AWSHTTPClient.swift
Sources/SotoCore/HTTP/AsyncHTTPClient.swift

So we can change it without requiring a major release
This will mean AsyncHTTPClient is the only HTTP client you can use with Soto

Make AWSHTTPClient internal to project

---

Sources/SotoCore/AWSServiceConfig.swift
Sources/SotoCore/Doc/AWSShape.swift
Sources/SotoCore/Message/AWSRequest.swift
Tests/SotoCoreTests/AWSRequestTests.swift

If you set `.calculateMD5` in the service config then any request which has an input shape with option `.md5ChecksumHeader` will have the its md5 checksum calculated and the value will be placed in the `Content-MD5` header.
This replaces the MD5 calculation in the S3 middleware.

MD5 checksum calculations

---

Sources/SotoCore/AWSShapes/Payload+async.swift
Sources/SotoCore/AsyncAwaitSupport/AWSClient+EndpointDiscovery+async.swift
Sources/SotoCore/AsyncAwaitSupport/AWSClient+Paginate+async.swift
Sources/SotoCore/AsyncAwaitSupport/AWSClient+Waiter+async.swift
Sources/SotoCore/AsyncAwaitSupport/AWSClient+async.swift
Sources/SotoCore/AsyncAwaitSupport/AWSService+async.swift
Sources/SotoCore/AsyncAwaitSupport/CredentialProvider+async.swift
Sources/SotoTestUtils/TestUtils+async.swift
Tests/SotoCoreTests/AWSClientTests+async.swift
Tests/SotoCoreTests/AWSServiceTests+async.swift
Tests/SotoCoreTests/Credential/CredentialProviderTests+async.swift
Tests/SotoCoreTests/EndpointDiscoveryTests+async.swift
Tests/SotoCoreTests/PaginateTests+async.swift
Tests/SotoCoreTests/WaiterTests+async.swift

Given the availability checks are causing issue in older Xcodes I'm thinking of reverting these changes

Revert availability check changes for earlier platform versions

---

.github/workflows/ci.yml
Sources/SotoCore/AWSEndpointDiscovery.swift
Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift
Sources/SotoCore/HTTP/S3StreamReader.swift
Tests/SotoCoreTests/AWSClientTests+async.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/AWSRequestTests.swift
Tests/SotoCoreTests/AWSResponseTests.swift
Tests/SotoCoreTests/Credential/CredentialProviderTests.swift
Tests/SotoCoreTests/Credential/RotatingCredentialProviderTests.swift
Tests/SotoCoreTests/EndpointDiscoveryTests+async.swift
Tests/SotoCoreTests/EndpointDiscoveryTests.swift

Without the Sendable conformance (basically gave up). I thought the other changes would still be useful though
Adding final to classes
making member variables private where required
Use `NIOLock<Int>` in tests, instead of raw `Int`'s

Prep for Sendable conformance

---

.github/workflows/ci.yml
Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Credential/ConfigFileLoader.swift
Sources/SotoCore/Credential/MetaDataCredentialProvider.swift
Sources/SotoCore/Credential/RotatingCredentialProvider.swift
Sources/SotoCore/HTTP/S3StreamReader.swift
Sources/SotoCore/HTTP/StreamWriter+write.swift
Sources/SotoCore/Message/AWSRequest.swift
Sources/SotoXML/Expat.swift
Tests/SotoCoreTests/AWSRequestTests.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Tests/SotoCoreTests/DictionaryEncoderTests.swift
Tests/SotoCoreTests/QueryEncoderTests.swift
Tests/SotoCoreTests/ValidationTests.swift

Body should still contain Version and Action keys. It appears some services don't care but SES does see https://github.com/soto-project/soto/issues/580
Most of the changes in here are related to a new version of swift format. See #494 where changes are being merged into main branch

Fix empty query protocol requests (5.x.x branch)

---

Sources/SotoCore/Message/AWSRequest.swift
Tests/SotoCoreTests/AWSRequestTests.swift

Body should still contain Version and Action keys. It appears some services don't care but SES does see https://github.com/soto-project/soto/issues/580

Fix empty query protocol requests

---

Sources/SotoSignerV4/signer.swift

Some non AWS S3 systems do not cope with non percent encoded version of these
characters

Remove chars "@()" from awsPathAllowedCharacters

---

Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

Remove content-type, content-length, expect and user-agent from signed headers list.
This is the same as AWS cli does.

Remove certain headers from signature

---

Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

The signer examples can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html#example-signature-calculations)
Add tests for these and fix one minor difference by removing space between items in authorization header

Add tests for AWS V4 Signer examples

---

Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

When a URL query parameter has no value, AWS expects it to be presented as `key=`. processURL did not add the `=` sign.
See https://github.com/soto-project/soto-core/issues/523

When a query parameter has no value, output is as `key=`

---

Sources/SotoCore/HTTP/S3StreamReader.swift
Sources/SotoCore/HTTP/StreamWriter+write.swift
Tests/SotoCoreTests/AWSClientTests.swift

Use `eventLoop.execute` instead of calling function directly. If streamed results are always available as soon as `streamChunks` is called it is the equivalent to a function call which can then mount up and cause a stack overflow

Fix stack overflows generated when streaming requests

---

Tests/SotoCoreTests/Concurrency/AsyncSequenceTests.swift

Given we moved the type to Soto we can't tests it in SotoCore

Remove AsyncEnumeratedSequence tests

---

Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

This is from S3 sigV4 docs
The CanonicalHeaders list must include the following:
- HTTP host header.
- If the Content-Type header is present in the request, you must add it to the CanonicalHeaders list.
- Any x-amz-* headers that you plan to include in your request must also be added. For example, if you are using temporary security credentials, you need to include x-amz-security-token in your request. You must add this header in the list of CanonicalHeaders.

Don't remove content-type from signed headers

---

Sources/SotoCore/AWSClient+EndpointDiscovery.swift
Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Concurrency/AnyAsyncSequence.swift
Sources/SotoCore/Encoder/DictionaryDecoder.swift
Sources/SotoCore/HTTP/AWSHTTPTypes.swift
Sources/SotoCore/HTTP/AsyncHTTPClient.swift
Sources/SotoCore/Message/AWSResponse+HAL.swift
Sources/SotoCore/Message/AWSResponse.swift
Sources/SotoCore/Message/Middleware/LoggingMiddleware.swift
Sources/SotoCore/Message/Middleware/S3Middleware.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/AWSResponseTests.swift
Tests/SotoCoreTests/PayloadTests.swift
Tests/SotoCoreTests/TimeStampTests.swift

Replace old streaming functions that call a closure with an AsyncSequence (currently HTTPBody) added to the output type.

7.x.x: Response streaming

---

.github/workflows/ci.yml
Package.swift
Sources/SotoCore/Concurrency/EventStream.swift
Sources/SotoCore/Doc/AWSShape.swift
Sources/SotoCore/Encoder/EventStreamDecoder.swift
Sources/SotoCore/Encoder/ResponseContainer.swift
Sources/SotoCore/Message/AWSResponse.swift
Sources/SotoTestUtils/TestUtils.swift
Sources/SotoXML/Expat.swift
Tests/SotoCoreTests/AWSResponseTests.swift

See S3.SelectObjectContent, Lambda.InvokeWithResponseStream etc. You can see documentation on decoding these here https://docs.aws.amazon.com/AmazonS3/latest/API/RESTSelectObjectAppendix.html.
- Added an `AWSEventStream` type that reads from a base ByteBuffer async sequence.
- These buffers are passed to an EventStreamDecoder which decodes the headers and then passes payload onto relevant decoder.
Related PRs: https://github.com/soto-project/soto-codegenerator/pull/74, https://github.com/soto-project/soto/pull/686

Add support for decoding event streams

---

.github/workflows/codeql.yml

This removes the environment variable as Swift is out of beta so no longer needed. It also removes some permissions that are only required for private repositories.
We could also run this on Linux as CodeQL now supports 5.8 and Linux properly, but I've left it as macOS. Happy to switch it to Linux if it makes it easier (currently in Vapor I've opted for both to catch any issues just in case)

Simplify CodeQL file now it's out of Beta

---

Tests/SotoCoreTests/Concurrency/ExpiringValueTests.swift
Tests/SotoCoreTests/Credential/RotatingCredentialProviderTests.swift

There is a problem with the tests where we are checking an almost expired value in ExpiringValue

Fix ExpiringValue tests

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Concurrency/EventStream.swift
Sources/SotoCore/Doc/AWSShape+Encoder.swift
Sources/SotoCore/Encoder/EventStreamDecoder.swift
Sources/SotoCore/HTTP/AWSHTTPResponse.swift
Sources/SotoCore/Message/Middleware/S3Middleware.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/AWSResponseTests.swift
Tests/SotoCoreTests/Credential/ConfigFileLoaderTests.swift
Tests/SotoCoreTests/TimeStampTests.swift

SotoXML is an internal module which shouldn't be used outside of SotoCore

Import SotoXML as implementation only

---

Package.swift

Update to version which resolves https://github.com/swift-server/async-http-client/security/advisories/GHSA-v3r5-pjpm-mwgq

Require async-http-client 1.18.0

---

Package.swift

The low `swift-crypto` version is problematic.
I'm not sure if you actually meant that 🤔.
Also there is `.package(url: "https://github.com/apple/swift-metrics.git", "1.0.0"..<"3.0.0"),` which seems suspicious to me, so just want to point it out if you actually meant `"1.0.0"..<"3.0.0"`.
I have no idea, but thought doesn't hurt to mention it.

Soto 7.0.0-alpha.1: fix Package.swift versions

---

Sources/SotoCore/Credential/MetaDataCredentialProvider.swift
Sources/SotoCore/Encoder/CodableProperties/DateCoders.swift
Sources/SotoCore/Encoder/QueryEncoder.swift
Sources/SotoCore/Encoder/RequestContainer.swift
Sources/SotoXML/XMLDecoder.swift
Sources/SotoXML/XMLEncoder.swift
Tests/SotoCoreTests/AWSRequestTests.swift

Also 
- fixed an issue where headers are not output in date time format by default
- Added testHeaderDateEncoding

 Use ISO8601DateFormatter instead of DateFormatter

---

Package.swift
Sources/SotoCore/AWSClient.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Tests/SotoCoreTests/Credential/ConfigFileLoaderTests.swift

This is a duplicate of #584 but for the 7.x.x branch

Use singleton EventLoopGroup instead of using createNew

---

Package.swift

Per their [release notes](https://github.com/apple/swift-crypto/releases/tag/3.0.0), `"1.0.0" ..< "4.0.0"` is now the recommended range.
This resolves https://github.com/soto-project/soto-core/issues/587.

Bump swift-crypto version range to support latest major version release.

---

Sources/SotoCore/AWSClient.swift

Convert HTTPClientProvider to a struct so it can be extended without requiring a major version

Convert HTTPClientProvider to a struct

---

Sources/SotoCore/Encoder/RequestContainer.swift
Sources/SotoCore/Encoder/ResponseContainer.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/AWSRequestTests.swift
Tests/SotoCoreTests/AWSResponseTests.swift
Tests/SotoCoreTests/TimeStampTests.swift

Thoughts?
This hides public symbols in SotoCore that are required by Soto, but should not really be public to users of Soto

Hide request/response containers behind @_spi(SotoInternal)

---

Sources/SotoCore/Credential/MetaDataCredentialProvider.swift

JSONDecoder uses a lock to ensure it is Sendable. This is to avoid thread contention when multiple Tasks want to use this JSONDecoder

Don't store JSONDecoder in MetaDataClient

---

Sources/SotoCore/Middleware/Middleware/EndpointDiscoveryMiddleware.swift
Sources/SotoCore/Middleware/Middleware/S3Middleware.swift
Sources/SotoCore/Middleware/Middleware/TreeHashMiddleware.swift
Sources/SotoSignerV4/signer.swift

`Sequence.hexDigest` and `URL.pathWithSlash` both extend types we don't own so should not be part of the public interface

Use SotoInternal to hide extensions

---

Sources/SotoCore/Doc/AWSShape.swift

In Xcode15.3(now in RC), it shows many warnings of concurrency.

Add Sendable to AWSShapeOptions

---

Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift
Sources/SotoCore/Credential/CredentialProvider.swift
Sources/SotoCore/Credential/CredentialProviderError.swift
Sources/SotoCore/Credential/STSAssumeRole.swift
Sources/SotoCore/Credential/StaticCredential+Environment.swift
Sources/SotoTestUtils/TestUtils.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Tests/SotoCoreTests/Credential/STSAssumeRoleTests.swift
Tests/SotoCoreTests/Credential/StaticCredential+EnvironmentTests.swift
Tests/SotoCoreTests/LoggingTests.swift

Add support for `AWS_ROLE_ARN`, `AWS_ROLE_SESSION_NAME` and `AWS_WEB_IDENTITY_TOKEN_FILE` environment variables.
This ended up required more change than expected as it required another STS command merged into SotoCore. I have also tidied up a few things along the way.

Add support for AWS_ROLE_ARN environment variables

---

Package.swift
Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Credential/STSAssumeRole.swift
Sources/SotoTestUtils/TestUtils.swift
Tests/SotoCoreTests/AWSClientTests.swift
Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Tests/SotoCoreTests/Credential/STSAssumeRoleTests.swift
Tests/SotoCoreTests/EndpointDiscoveryTests.swift
Tests/SotoCoreTests/LoggingTests.swift
Tests/SotoCoreTests/PaginateTests.swift
Tests/SotoCoreTests/TracingTests.swift

Replace the `HTTPClientProvider` in `init` with a `AWSHTTPClient` protocol and default it to `HTTPClient.shared`.
@weissi Given your concern, this is the change I wanted to make. It now means AWSClient is not managing an `HTTPClient`.

Use HTTPClient.shared now that it is available

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/AWSServiceConfig.swift
Sources/SotoCore/Doc/ARN.swift
Sources/SotoCore/Middleware/Middleware.swift
Sources/SotoCore/Middleware/Middleware/S3Middleware.swift
Tests/SotoCoreTests/Doc/ARNTests.swift
Tests/SotoCoreTests/MiddlewareTests.swift

You can set up an accesspoint using S3Control.
This PR adds support for using this arn as a bucket name.
This has been tested with S3 access points
In theory this should also work for S3 outposts and S3 object lambdas (thus resolving https://github.com/soto-project/soto/issues/611).

Add support for S3 arn based access points

---

Sources/SotoCore/AWSClient.swift
Sources/SotoCore/Credential/CredentialProvider.swift
Sources/SotoCore/Credential/EmptyCredential.swift
Sources/SotoCore/HTTP/AWSHTTPBody.swift
Sources/SotoCore/Middleware/Middleware.swift
Sources/SotoCore/Middleware/Middleware/S3Middleware.swift
Sources/SotoCore/Middleware/Middleware/SigningMiddleware.swift
Tests/SotoCoreTests/AWSServiceTests.swift
Tests/SotoCoreTests/Credential/RuntimeSelectorCredentialProviderTests.swift
Tests/SotoCoreTests/MiddlewareTests.swift

- sets up the endpoint. It doesn't use the s3express signing process
- Adds credential to middleware context so that it can be accessed by s3 express middleware
- Add S3Middleware task local for settings specific to S3Middleware

Add support for S3 express endpoints

---

Sources/SotoCore/Encoder/CodableProperties/DateCoders.swift

Avoid  build error on Swift 6.1 under macOS:
```
soto-core/Sources/SotoCore/Encoder/CodableProperties/DateCoders.swift:112:23 Static property 'dateFormatter' is not concurrency-safe because non-'Sendable' type 'DateFormatter' may have shared mutable state
```
Linux compiles fine.
Fixes https://github.com/soto-project/soto-core/issues/633

Build on Swift 6.1 under macOS Static property 'dateFormatter' is not concurrency-safe

---

Sources/SotoCore/Encoder/EventStreamDecoder.swift
Tests/SotoCoreTests/AWSResponseTests.swift

This adds support for decoding `exception` events from an event stream. 
Example stream with exception events: [bedrockagentruntime#ResponseStream](https://github.com/aws/aws-sdk-go-v2/blob/f0d143d1fb449b320ac5ff0b2c513812a51d9904/codegen/sdk-codegen/aws-models/bedrock-agent-runtime.json#L7491)

Support Exception Events

---

Sources/SotoSignerV4/HexEncoding.swift
Sources/SotoSignerV4/SigV4a.swift
Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/SigV4aTests.swift

- Tested signing manually against S3 for both query and header
- Writing a full test case is hard, as signing ECDSA signing is non deterministic
- Added new HexEncoding mode, that can be used to make `hexDigest()` much faster :)
Fixes: #532

Add support for sigV4a signing

---

Sources/SotoCore/Middleware/Middleware/S3Middleware.swift
Tests/SotoCoreTests/MiddlewareTests.swift

If URL `/` is passed in the split of the path returns a bucket name of "". This should be assumed to mean we have no bucket so don't do the S3 virtual address mixup.

Don't apply S3 virtual address fixup if bucket is ""

---

Sources/SotoCore/Doc/AWSShape.swift
Sources/SotoCore/Errors/Error.swift
Sources/SotoCore/HTTP/AWSHTTPResponse.swift
Tests/SotoCoreTests/AWSResponseTests.swift

At the moment I have to attach an existential to the standard error to avoid a breaking change. If we ever release a 8.0 I'll look to throw concrete versions of these errors.
This is to support https://github.com/soto-project/soto/issues/761

Add ability to decode custom errors

---

Sources/SotoCore/HTTP/AWSHTTPRequest.swift
Tests/SotoCoreTests/AWSRequestTests.swift

HTTP DELETE methods should not include a body. We were only checking for GET and HEAD method requests previously. It wasn't an issue but AWS lambda is now returning a signing error because of this. So I've added a check for DELETE method in the serialisation of json bodies.
EDIT: Verified it fixes signing issue with deleting lambdas

Don't output body for json DELETE requests

---

Sources/SotoSignerV4/signer.swift
Tests/SotoSignerV4Tests/AWSSignerTests.swift

As reported in #655 OpenSearchServerless expects spaces in the Authorization header
I verified that aws-cli also adds spaces in between the sections of the Authorization header as well.

Add spaces in Authorization header

---

.github/workflows/ci.yml
Sources/SotoCore/Doc/Environment.swift
Sources/SotoTestUtils/Environment.swift
Sources/SotoXML/Expat.swift
Tests/SotoCoreTests/Credential/StaticCredential+EnvironmentTests.swift

The goal of this pull request is to add Android support to soto-core.
The following changes were verified on the swift-6.1 toolchain built for
Android.
soto-core should work flawlessly against an android swift toolchain
(tested with version 6.1) with the same limitations and context as the
current support on Linux + Windows.
No new unit tests were added.
tested on android api level 30
---------

Adding Android support

---

Package.swift

My swift implementation of jmespath has moved to the official jmespath org. Lets use it

Use jmespath.swift from jmespath org
