soto-project/soto-core

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/DictionaryConvertible/DictionaryConvertible.swift
- Tests/AWSSDKSwiftCoreTests/SerializableTests.swift
https://github.com/noppoMan/aws-sdk-swift/issues/45
> add serializeToFlatDictionary to create valid query string for services that use query service protocol

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Signers/V4.swift
- Tests/AWSSDKSwiftCoreTests/SignersV4Tests.swift
Reverts noppoMan/aws-sdk-swift-core#19
> Revert "Fix SignatureDoesNotMatch in some s3's operations"

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Serializer/XMLNodeSerializer.swift
- Tests/AWSSDKSwiftCoreTests/SerializersTests.swift
Do not create "member" key in dictionary structure
> serialize elements to json that are called "Member" with special logic

- Package.swift
- Sources/AWSSDKSwiftCore/HTTPClient.swift
instead of rewriting ByteBuffer extension in HTTPClient
> 39 use NIOFoundationCompat 

- Sources/AWSSDKSwiftCore/Hash.swift
This is necessary to implement Glacier TreeHash checksum
> implement sha of shas in the hash lib

- Sources/AWSSDKSwiftCore/Encoder/AWSShapeEncoder.swift
> Fixed query encoding of arrays

- .travis.yml
[Reported](https://discordapp.com/channels/431917998102675485/472522745067077632/574525822505844780) by @adam-fowler
> Quiet the xcodebuild logs and run in parallel

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
> fix HEAD requests

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
so clients can chain off the response and catch errors
forgive the lack of test, this is tough to test without calling out to aws...
> return Future<Void> instead of Void

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Encoder/AWSShapeEncoder.swift
- Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
- Sources/AWSSDKSwiftCore/Encoder/XMLEncoder.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
- Tests/AWSSDKSwiftCoreTests/SerializersTests.swift
- Tests/AWSSDKSwiftCoreTests/TimeStampTests.swift
Making the XML Encoder/Decoder more similar to the JSON versions. 
Adding data and date coding options.
Supporting nestedContainers, superEncoders
> Xmlcodable changes

- Sources/AWSSDKSwiftCore/XML.swift
- Tests/AWSSDKSwiftCoreTests/XMLTests.swift
Replicating behaviour of Foundation
> XML: If text is completely white space don't add a text node

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Encoder/XMLDecoder.swift
- Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Needed to add this to fix S3.GetBucketLocation does not return a location https://github.com/swift-aws/aws-sdk-swift/issues/157
> Added Middleware editing of response bodies

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Signers/V4.swift
- Tests/AWSSDKSwiftCoreTests/SignersV4Tests.swift
eg Pinpoint signing name is "mobiletargeting"
> Some services have a different signing name to their service name

- Sources/AWSSDKSwiftCore/AWSClient.swift
reverting change from previous merge
> Made AWSClient.eventGroup public

- Sources/AWSSDKSwiftCore/AWSClient.swift
Previously if we were processing an XML response the values stored in the response headers were never processed. This change ensures they are.
> If processing an XML response ensure we also process the header values

- .github/workflows/swift.yml
- README.md
Integration with github actions.
Compared to Travis it is faster, but the UI seems a little clunky at the moment. 
Thought we could have both running for a while to see which works better.
> GitHub actions

- .github/workflows/swift.yml
What else do we want to achieve with this pr?
Looking forward to your feedback: @adam-fowler @Yasumoto @jonnymacs
> Improvements to GitHub Actions

- Sources/AWSSDKSwiftCore/AWSClient.swift
Tidied up switch in createNioRequest() as detailed in #150
> Tidied switch in createNioRequest()

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/MetaDataService.swift
- Sources/AWSSDKSwiftCore/Signers/V4.swift
- deprecated typealias Future
- removed all uses of public Future
will make transition in 5.0 easier.
> Deprecated typealias Future

- Sources/AWSSDKSwiftCore/AWSClient+HAL.swift
- Sources/AWSSDKSwiftCore/AWSClient.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
- Moved HAL code into separate file
- Removed link loading as the code doesn't work and never seems to get used
- Added test for processing json+hal files
> Hypertext application language process refactor

- Sources/AWSSDKSwiftCore/MetaDataService.swift
This is causing issues with processes running inside containers. The process attempts to connect to the instance metadata service to get the session token. The connection is made but the request nevers completes. Out HTTPClient doesn't deal with this, it only has a connection timeout. Luckily AsyncHTTPClient also has an idle timeout and deals with this so we only need to disable this on the 4.x.x branch.
> Disabling Instance Metadata service v2 into 4.x.x branch

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Error.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Fix bug where responses with raw payloads were not parsing errors correctly
Add response statusCode to AWSError
> Error handling changes

- NOTICE.txt
- Package.swift
- Sources/INIParser/INIParser.swift
Also added NOTICE.txt indicating where INIParser came from
> Vendor INIParser

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Deal with query responses that have their error inside an "Errors" xml element
- restjson error codes are sometimes available in the response body
- Added EC2 error parsing
> Error handling fixes

- Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift
- Tests/AWSSDKSwiftCoreTests/QueryEncoderTests.swift
- Tests/AWSSDKSwiftCoreTests/TestUtils.swift
- Tests/AWSSignerTests/AWSSignerTests.swift
Use this to control whether performance tests run
ENABLE_TIMING_TESTS=false will disable performance tests
> Added ENABLE_TIMING_TESTS environment variable

- .github/workflows/ci.yml
This gives us a much more realistic coverage result
> CI: Disable performance tests, Don't upload coverage for Tests folder

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSignerV4/signer.swift
- Tests/AWSCryptoTests/AWSCryptoTests.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
- Tests/AWSSDKSwiftCoreTests/CredentialTests.swift
- Tests/AWSSDKSwiftCoreTests/ValidationTests.swift
- Tests/AWSSignerTests/AWSSignerTests.swift
Added more tests for AWSCrypto, AWSSigner, INIParser, AWSClient
> Improve test coverage

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Used by APIGateway.GetExportRequest.parameters.
> Add query serialization for dictionaries

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Credential/Credential.swift
- Sources/AWSSDKSwiftCore/Doc/Environment.swift
- Sources/AWSSDKSwiftCore/Doc/Mirror.swift
- Sources/AWSSDKSwiftCore/MetaDataService.swift
- Sources/AWSSDKSwiftCore/ServiceConfig.swift
- Sources/AWSSignerV4/credentials.swift
- Tests/AWSSDKSwiftCoreTests/Doc/EnvironmentTests.swift
- Tests/AWSSDKSwiftCoreTests/MetaDataServiceTests.swift
- Tests/AWSSDKSwiftCoreTests/TestUtils.swift
We want to lower dependencies on Foundation. 
- Removed dependency on `ProcessInfo.processInfo.environment`
- Added an `Environment` namespace
- Added `Environment[subscript] -> String?` to read env variables.
> Reading environment variable from C

- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Stopped using the global AWSClients. Create AWSClient with createAWSClient()
> Clean AWSClientTests up a little

- .github/workflows/sanity.yml
- Sources/AWSSDKSwiftCore/Doc/Environment.swift
Currently only checks for file headers
Could include running swift-format #270
> Run sanity.sh on PRs

- Sources/AWSSDKSwiftCore/Credential/StaticCredential+Shared.swift
- Tests/AWSSDKSwiftCoreTests/Credential/StaticCredential+SharedTests.swift
Bring fixes for static credentials from @fabianfett across 
Without these fixes ~/.aws/credential file is broken
> Fixes for StaticCredentials from file

- Sources/AWSSDKSwiftCore/RetryPolicy.swift
Minor change to Jitter calculation
> Make retry policy time calculation more in line with aws-sdk-go

- Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
- Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
Set User-Agent header to "AWSSDKSwift/5.0" as request by Todd Varland from AWS
> Set user-agent header

- Sources/AWSSDKSwiftCore/HTTP/NIOTSHTTPClient.swift
When using NIOTSHTTPClient the head uri was getting set to the full URL, when it should be the path relative to the web address.
I've stolen some code to get the relative path from AsyncHTTPClient to ensure this is consistent between the two clients. This is a temporary fix as we'll be moving to AHC for all platforms when 1.2 is released.
> Fix head uri for NIOTSHTTPClient

- Sources/AWSSDKSwiftCore/HTTP/AsyncHTTPClient.swift
- Sources/AWSSDKSwiftCore/HTTP/ResponseDelegate.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
This is to get around a bug in AsyncHTTPClient https://github.com/swift-server/async-http-client/issues/274 where the streaming delegate tasks can still be running even when the client says it is done
> Wait on streaming delegate to be finished

- .github/workflows/swift.yml
- Sources/AWSSDKSwiftCore/Encoder/AWSShapeEncoder.swift
PR #216 applied to 3.x.x branch
> Support Data encoding in the query encoder in 3.x.x

- Sources/AWSSDKSwiftCore/Credential/RotatingCredentialProvider.swift
Don't think this needs to be a generic
Kick off a `refreshCredential` as soon as the provider is created, so we don't wait until the first request to get credentials
> Minor changes to RotatingCredentialProvider

- Sources/AWSSDKSwiftCore/AWSServiceConfig.swift
- Sources/AWSSDKSwiftCore/Doc/AWSShape.swift
- Sources/AWSSDKSwiftCore/Doc/Region.swift
- Sources/AWSTestUtils/TestUtils.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
- Tests/AWSSDKSwiftCoreTests/AWSResponseTests.swift
- Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
- scripts/templates/generate-region/Region.stencil
Partition -> AWSPartition
PayloadOptions -> AWSShapePayloadOptions
> Public symbol rename

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/AWSServiceConfig.swift
- Sources/AWSSDKSwiftCore/Exports.swift
- Sources/AWSTestUtils/TestUtils.swift
Allow user to define their own timeout for HTTP requests to AWS
> Add HTTPClient timeout to AWSServiceConfig

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Exports.swift
- Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
- Tests/AWSSDKSwiftCoreTests/AWSRequestTests.swift
- Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
- Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
- Tests/AWSSDKSwiftCoreTests/PerformanceTests.swift
- Tests/AWSSDKSwiftCoreTests/TimeStampTests.swift
Replace httpMethod string in execute methods with enum NIOHTTP1.HTTPMethod
> Replace httpMethod string in with enum NIOHTTP1.HTTPMethod

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
This only works for the situation where the AWSClient was initialised with a shared HTTPClient.
Waiting on AsyncHTTPClient 1.2.0 to implement the async shutdown of HTTPClient.
> Add async shutdown func

- .github/workflows/ci.yml
- Sources/AWSTestUtils/TestUtils.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
- Tests/AWSSDKSwiftCoreTests/AWSResponseTests.swift
- Tests/AWSSDKSwiftCoreTests/Credential/ConfigFileCredentialProviderTests.swift
- Tests/AWSSDKSwiftCoreTests/Credential/CredentialProviderTests.swift
- Tests/AWSSDKSwiftCoreTests/Credential/MetaDataCredentialProviderTests.swift
- Tests/AWSSDKSwiftCoreTests/Credential/RotatingCredentialProviderTests.swift
- Tests/AWSSDKSwiftCoreTests/Credential/RuntimeSelectorCredentialProviderTests.swift
- Tests/AWSSDKSwiftCoreTests/HTTPClientTests.swift
- Tests/AWSSDKSwiftCoreTests/PaginateTests.swift
- Tests/AWSSDKSwiftCoreTests/PayloadTests.swift
Enable logger in tests with environment variable AWS_LOG_LEVEL=trace,info etc
> Added Loggers to Tests

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/Message/AWSRequest.swift
- Tests/AWSSDKSwiftCoreTests/AWSClientTests.swift
Allows us to extend it without required a major version update
> Make AWSClient.ClientError a struct

- Sources/AWSSDKSwiftCore/AWSService.swift
Adds helper functions/vars region, endpoint, eventLoopGroup and signURL to all services
> Add AWSService protocol

- Sources/AWSSDKSwiftCore/AWSClient.swift
- Sources/AWSSDKSwiftCore/HTTP/S3StreamReader.swift
All other execute functions call this.
Allows us to centralize some of the common functionality
> Added common AWSClient.execute function

- Sources/SotoSignerV4/signer.swift
Had to do the parsing myself, as there are no URL functions available for all macOS versions that would tell me if a path ended with a slash.
Fixes signing of Lambda.ListFunctions
> Extend URL with pathWithSlash and use in Signer

- Sources/SotoCore/Message/AWSResponse.swift
Message key can be capitalized but sometimes it isnt
version 2 of this didnt like the previous one
> Allow for json error messages with capitalized key

- Sources/SotoCore/Message/AWSRequest.swift
- Tests/SotoCoreTests/AWSRequestTests.swift
Bloody pain working with URLComponents. Gonna try and remove it from the equation later
> Percent encode path again after extracting from URLComponents

- Sources/SotoCore/AWSClient.swift
... and use it to create the promise for the finished invoke instead of using the eventLoopGroup attached to the http client
> Pass eventLoop to AWSClient.invoke

- Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift
- Sources/SotoCore/Credential/CredentialProvider.swift
- Sources/SotoCore/Credential/CredentialProviderSelector.swift
- Sources/SotoCore/Credential/RuntimeSelectorCredentialProvider.swift
- Sources/SotoCore/Credential/STSAssumeRole.swift
- Tests/SotoCoreTests/Credential/ConfigFileCredentialProviderTests.swift
Used by ConfigFile credential provider
> Add internal version of STS AssumeRole credential provider

- .github/workflows/sanity.yml
- .swiftformat
- Sources/SotoCore/AWSClient+Paginate.swift
- Sources/SotoCore/AWSServiceConfig.swift
- Sources/SotoCore/Credential/ConfigFileCredentialProvider.swift
- Sources/SotoCore/Encoder/DictionaryDecoder.swift
- Sources/SotoCore/Message/AWSResponse+HAL.swift
- Sources/SotoCore/Message/AWSResponse.swift
- Sources/SotoTestUtils/TestServer.swift
- Sources/SotoTestUtils/TestUtils.swift
- Tests/SotoCoreTests/AWSResponseTests.swift
Disable extensionAccessControl
> Upgrade to SwiftFormat v0.47.4

- Sources/SotoCore/AWSClient.swift
- Sources/SotoCore/Message/AWSMiddleware.swift
- Sources/SotoTestUtils/TestUtils.swift
- Tests/SotoCoreTests/AWSClientTests.swift
- Tests/SotoCoreTests/LoggingTests.swift
- Add `AWSLoggingMiddleware.init(logger:logLevel)`
- Add `AWSClient.Options` with field for defining the request logging level
> Logging changes

- Sources/SotoCore/AWSClient+Paginate.swift
- Sources/SotoSignerV4/signer.swift
- Tests/SotoCoreTests/PaginateTests.swift
Add paginate function that takes in an inputToken as well as outputToken. If outputToken is equal to inputToken then consider paginate to be finished
> Paginate input token test

- Sources/SotoCore/AWSClient.swift
- Tests/SotoCoreTests/LoggingTests.swift
Also make retry logging trace
This change is in response to https://github.com/swift-server/guides/blob/main/log-levels.md
> Add `AWSClient.Options.errorLogLevel`

- Sources/SotoCore/AWSClient+EndpointDiscovery+async.swift
- Sources/SotoCore/AWSClient+Paginate+async.swift
- Sources/SotoCore/AWSClient+async.swift
- Sources/SotoCore/AWSService+async.swift
- Sources/SotoCore/AWSShapes/Payload+async.swift
- Sources/SotoCore/Credential/CredentialProvider+async.swift
- Sources/SotoCore/Waiters/AWSClient+Waiter+async.swift
- Sources/SotoTestUtils/TestUtils+async.swift
- Tests/SotoCoreTests/AWSClientTests+async.swift
- Tests/SotoCoreTests/AWSServiceTests+async.swift
- Tests/SotoCoreTests/Credential/CredentialProviderTests+async.swift
- Tests/SotoCoreTests/EndpointDiscoveryTests+async.swift
- Tests/SotoCoreTests/PaginateTests+async.swift
- Tests/SotoCoreTests/TimeStampTests.swift
- Tests/SotoCoreTests/WaiterTests+async.swift
See https://github.com/apple/swift-nio/pull/1966#discussion_r714110863
> Wrap concurrency code in canImport(_Concurrency)

- Sources/SotoCore/Message/AWSRequest.swift
- Tests/SotoCoreTests/AWSClientTests.swift
Change user-agent from Soto/5.0 to Soto/6.0
> User-agent header -> Soto/6.0

- Sources/SotoCore/AWSServiceConfig.swift
S3 code is in branch https://github.com/soto-project/soto/tree/feature/disable-s3-100-continue. I'll create a PR for that once this flag is in a release.
> Add new service flag `.s3Disable100Continue`

- Sources/SotoCore/Message/AWSMiddleware.swift
- Sources/SotoCore/Message/AWSRequest.swift
- Sources/SotoCore/Message/Middleware/EditHeadersMiddleware.swift
- Sources/SotoCore/Message/Middleware/LoggingMiddleware.swift
- Sources/SotoTestUtils/TestServer.swift
- Tests/SotoCoreTests/AWSClientTests.swift
Middleware for adding, replacing, removing headers. 
Also moved some code about.
> Add AWSEditHeadersMiddleware

- Sources/SotoCore/Credential/MetaDataCredentialProvider.swift
- Sources/SotoCore/Message/Middleware/EditHeadersMiddleware.swift
- Tests/SotoCoreTests/AWSRequestTests.swift
- Tests/SotoCoreTests/DictionaryEncoderTests.swift
> Make AWSEditHeadersMiddleware.init public

- Sources/SotoCore/Middleware/Middleware.swift
- Sources/SotoCore/Middleware/Middleware/EditHeadersMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/EndpointDiscoveryMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/ErrorHandlingMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/LoggingMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/RetryMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/S3Middleware.swift
- Sources/SotoCore/Middleware/Middleware/SigningMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/TracingMiddleware.swift
- Sources/SotoCore/Middleware/Middleware/TreeHashMiddleware.swift
Shortens signature of function `AWSMiddlewareProtocol.handle`
> Add typealias AWSMiddlewareNextHandler

- .github/workflows/ci.yml
- Sources/SotoCore/AWSClient.swift
- Sources/SotoCore/Credential/CredentialProvider.swift
- Sources/SotoCore/Credential/MetaDataCredentialProvider.swift
- Sources/SotoCore/Credential/STSAssumeRole.swift
- Sources/SotoCore/HTTP/AWSHTTPBody.swift
- Sources/SotoCore/HTTP/AWSHTTPClient.swift
- Sources/SotoCore/HTTP/AWSHTTPRequest.swift
- Sources/SotoCore/HTTP/AWSHTTPResponse.swift
- Sources/SotoCore/HTTP/AsyncHTTPClient.swift
> Add AWSHTTPClient (2nd attempt)

- Sources/SotoCore/RetryPolicy.swift
Should hopefully resolve https://swift-open-source.slack.com/archives/C9MMT6VGB/p1729105368363359
> Retry on connection closed errors

- Package.swift
This PR updates the transitive dependencies of soto-s3-file-transfer to their latest versions ensuring improved compatibility and long-term maintainability.
> Update Transitive Dependencies for soto-s3-file-transfer

- Sources/SotoCore/AWSShapes/Document.swift
- Tests/SotoCoreTests/AWSRequestTests.swift
- Tests/SotoCoreTests/AWSResponseTests.swift
See https://smithy.io/2.0/spec/simple-types.html#document
Fixes https://github.com/soto-project/soto/issues/753
> Add AWSDocument type for arbitrary data

- .github/workflows/ci.yml
- Benchmark/Sources/soto-benchmark/EncoderSuites.swift
- Package.swift
- Sources/SotoCore/Credential/ExpiringCredential.swift
- Sources/SotoCore/Credential/MetaDataCredentialProvider.swift
- Sources/SotoCore/Credential/STSAssumeRole.swift
- Sources/SotoCore/Encoder/CodableProperties/DateCoders.swift
- Sources/SotoCore/Encoder/EventStreamDecoder.swift
- Sources/SotoCore/Encoder/QueryEncoder.swift
- Sources/SotoCore/Encoder/RequestContainer.swift
- Sources/SotoCore/Encoder/ResponseContainer.swift
- Sources/SotoCore/HTTP/AWSHTTPRequest.swift
- Sources/SotoCore/HTTP/AWSHTTPResponse.swift
- Sources/SotoCore/Middleware/Middleware/S3Middleware.swift
- Sources/SotoXML/XMLDecoder.swift
- Sources/SotoXML/XMLEncoder.swift
- Tests/SotoCoreTests/AWSClientTests.swift
- Tests/SotoCoreTests/AWSRequestTests.swift
- Tests/SotoCoreTests/Concurrency/ExpiringValueTests.swift
- Tests/SotoCoreTests/Credential/RotatingCredentialProviderTests.swift
- Tests/SotoCoreTests/MiddlewareTests.swift
- Tests/SotoCoreTests/TimeStampTests.swift
- Tests/SotoCoreTests/TracingTests.swift
Also updated user-agent header
> Swift 6.1, drop 5.9

- Sources/SotoCore/Credential/RotatingCredentialProvider.swift
- Tests/SotoCoreTests/Credential/RotatingCredentialProviderTests.swift
Add a threshold to expiration for when RotatingCredentialProvider returns valid credentials.
Previous there was one threshold. When you were within this threshold of credentials expiring, it would request new credentials, but still use the old ones as they were still valid. This has one issue though, the credential provider can return credentials that will expire in the next millisecond as valid.
This PR adds a second threshold. If within this threshold then the credential provider will wait until new credentials are available, instead of return the old credentials. By default this has been set to 15 seconds, but you can override it in the initializer for RotatingCredentialProvider.
> Valid credential threshold
